apiVersion: v1
kind: Service
namespace: dev
metadata:
  name: greendep
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
